### PR TITLE
WIP: Add models

### LINKED ISSUE #4: Create ERD (Database)

### PR DESCRIPTION
**Pull request by emmandev**

### CODE REVIEW

**Comment by emmandev** [comment]
@renesansz @phillip-atr mao lang sa gibutang nako na models ug ila fields kay unsure ko sa uban unsay better na implementation. Suggest lang mo.

**Comment by renesansz** [comment]
@emmandev thanks
@phillip-atr pa add ko atong missing tables (eg: users tables) na wala na mention sa imong diagram

**Comment by phillip-atr** [comment]
image

**Comment by phillip-atr** [comment]
with user table na pero naa koy i try dungag. I butang lang nko taod2.

**Comment by phillip-atr** [comment]
image

**Comment by phillip-atr** [comment]
image

**Comment by phillip-atr** [comment]
image

**Comment by renesansz** [comment]
for now, I think this basic data is enough. @phillip-atr pa add na lang sa PR commit ang pag apply sa user table

**Review by renesansz — CHANGES_REQUESTED** [review]
@phillip-atr  Please add the Users table in the PR, before ma approve for merge.

**Comment by phillip-atr** [comment]
Updated ERD
image

**Comment by phillip-atr** [comment]
@renesansz na add na nko.

**Review by renesansz — APPROVED** [review]
thanks @phillip-atr . approved and merged PR.

**Pull request merged**
